# Book settings
title: My sample book
author: The Jupyter Book Community
logo: logo.png

latex:
  latex_documents:
    targetname: book.tex

launch_buttons:
  notebook_interface        : "jupyterlab"  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : "https://mybinder.org"
  thebelab                  : true

repository:
  url                         : https://github.com/cedeerwe/test_book
  path_to_book                : "test-book"

sphinx:
  config:
    mathjax_config:
      TeX:
        Macros:
          "N": "\\mathbb{N}"
          "qq": ["\\quad#1\\quad", 1]